### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
As [discussed here](https://gitlab.com/IzzyOnDroid/repo/-/issues/280#note_1031597661). After merging, please add a few screenshots in `/fastlane/metadata/android/en-US/images/phoneScreenshots`. Of course you can also add other things, like a featureGraphic, per-release changelogs, descriptions for other languages… Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for orientation, and my [formatting help for full_description](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) if you want/need to update `full_description.txt`.

Last note: `en-US` is always used as fallback for "missing items" in other languages. So should you add other languages, there's no need to duplicate stuff (like screenshots or icon): what's not there, will simply be taken from `en-US`.

### CODE REVIEW

**Comment by varbhat** [comment]
@IzzySoft , Thanks. i will update it soon(currently busy with some other tasks).

**Comment by IzzySoft** [comment]
@varbhat you could also simply merge it now and build upon it later. Merging is just pushing a button, the other part indeed needs a few more minutes :wink:

**Comment by IzzySoft** [comment]
Thanks! Just let me know then when you've got a release APK ready, and we can proceed with the inclusion to my repo. Until then, best luck and good progress with that's keeping you busy!

**Comment by IzzySoft** [comment]
Is there any chance a release APK will become available – or have you given up on the project?

**Comment by varbhat** [comment]
@IzzySoft I am busy with University for the moment hence the inactivity. I plan to be more active from next month onwards and yeah, the the release APK will be available. Also, I need to take screenshots of the app.

**Comment by IzzySoft** [comment]
Doesn't look like it will be done any time soon™ – so I've now closed [your request](https://gitlab.com/IzzyOnDroid/repo/-/issues/280). Once you pick up again, be welcome to reopen so we can proceed. Meanwhile, all the best for your university tasks!

**Pull request merged**
